### ISSUE TITLE
README instructions do not match for Example output

### ISSUE THREAD

**Issue by nathanhannig** [freeCodeCamp/boilerplate-project-timestamp#1]
User story lists output to be 
{"unix": 1479663089000 ,"utc": "Sun, 20 Nov 2016 17:31:29 GMT"}

Example output at bottom of README has it in a different format as
{ "unix": 1450137600, "natural": "December 15, 2015" }

**Comment by breakpoint25** [comment]
index.html also has Example usage as
GET project url]/api/timestamp/1450137600

But I assume you want this to be 
GET project url]/api/timestamp/1450137600000

so it matches other screens

**Comment by aldaircruz** [comment]
I noticed that this [PR](https://github.com/freeCodeCamp/boilerplate-project-timestamp/pull/5) solve most of the problems reported.
Solves:
- [x] - [Example not in utc] (https://github.com/freeCodeCamp/boilerplate-project-timestamp/pull/5/commits/427c74fea919d803fc81513a8193278454ee32f7#diff-04c6e90faac2675aa89e2176d2eec7d8R20);
- [x] - [Typo in unix timestamp input] (https://github.com/freeCodeCamp/boilerplate-project-timestamp/pull/5/commits/427c74fea919d803fc81513a8193278454ee32f7#diff-f1891d0fc991bc126181b34bc856fa29R52)
- [ ] - [Url for glitch example not available]. Updated the glitch, however didn't use the one from the project.

In addition has some style improvements;

**Comment by hdansin** [comment]
In user story 5, there is discrepancy between the README/index.html and what it tests for.

Currently says the output for invalid date should be: `{"unix": null, "utc" : "Invalid Date" }` 
However the challenge tests for: `{"error" : "Invalid Date" }`

Threw me for a bit of a loop when I was trying to complete it.

**Comment by moT01** [comment]
Thanks for the reports everyone. I believe these are all fixed. If anyone still sees an issue, let me know and we can look into it.
