### ISSUE TITLE
Invalid date format doesn't pass tests

### ISSUE THREAD

**Issue by elchicofrommo** [freeCodeCamp/boilerplate-project-timestamp#29]
Looking at the instructions for invalid date format it specifies the response should be

{"unix": null, "utc" : "Invalid Date" }

however, the example on https://curse-arrow.glitch.me/api/timestamp/xxx as well as the tests from   https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/timestamp-microservice will not pass unless the format is 

{error: "Invalid Date" }

Please update the spec to reflect the test.

**Comment by moT01** [comment]
Looks like this got fixed @elchicofrommo. Both the website and the glitch boilerplate instruct to use the second variant now. If I am mistaken or you still think there's a problem, let us know.
