### ISSUE TITLE
Requirements specify input is ISO-8601 but tests allow for MS as string

### ISSUE THREAD

**Issue by elchicofrommo** [freeCodeCamp/boilerplate-project-timestamp#30]
The spec for this api says the input should be ISO-8601, which does not specify anything about a String of integer as miliseconds. Please update the readme as well as index.html to indicate that it accepts both ISO-8601 as well as a string representing MS since xxx

**Comment by moT01** [comment]
I don't see it saying the input is required to be ISO-8601.

> A date string is valid if can be successfully parsed by new Date(date_string). Note that the unix timestamp needs to be an integer (not a string) specifying milliseconds. In our test we will use date strings compliant with ISO-8601 (e.g. "2016-11-20") because this will ensure an UTC timestamp.

**Comment by moT01** [comment]
Please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
